### ISSUE TITLE
Cannot install CSPY latest version

### ISSUE THREAD

**Issue by jujaramillo** [torressa/cspy#100]
Hi @torressa!! I hope everything is find, please I need your help so much.

**Describe the bug**
I'm tryng to install the CSPY 1.0.1 version with PIP but it gives me this error "ERROR: Could not find a version that satisfies the requirement cspy==1.0.1 (from versions: 0.0.1, 0.0.2, 0.0.4, 0.0.5, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.1.0, 0.1.1, 0.1.2, 1.0.0a0)
ERROR: No matching distribution found for cspy==1.0.1"

**To Reproduce**
pip install cspy==1.0.1

Have a nice day.

**Comment by torressa** [comment]
Hey @jujaramillo, sorry for the delay.
To be able to help I need to know what OS you are on (Windows, MacOS or Linux) and the version of Python. Currently, there is a limited number of wheels due to hardware restrictions. You can find the list of wheels here: https://pypi.org/project/cspy/#files.
If your OS + architecture + Python Version doesn't match the ones in the list I can try and build one for you, but I cannot promise anything.
