### ISSUE TITLE
Update REF Callback Docs

### ISSUE THREAD

**Issue by tomatoes-prog** [torressa/cspy#68]
**Describe the bug**
The is simply, I am trying to create my own REF_callback for a CG problem, so I need to use the REFCallback class, to create de forward, backward and join functions, but I cannot import the Class and apparently it doent exist. The docs seems outdated, I would like to know how to implement this in the 0.1.2 version thanks.

**To Reproduce**
1. `pip install cspy`
2. `from cspy import REFCallback`

**Comment by torressa** [comment]
Hey! 
The docs are the most recent version v1.0 which is still in alpha stage (but it is orders of magnitude faster, see [here](https://github.com/torressa/cspy/releases/tag/v1.0.0-alpha)).

```
pip install cspy==1.0.0a0
```

I'd strongly recommend you upgrade to this version, for which (other than what's in the docs) you can see a good example of custom REFs for the VRP [here](https://github.com/Kuifje02/vrpy/blob/dev/vrpy/subproblem_cspy.py) (note that the backward and joining functions have been commented but they work! I was having some issues with the `direction="both"`).

If your code heavily relies on v0.1.2, you can still see the old documentation by browsing the repo under the 0.1.2 tag ([docs](https://github.com/torressa/cspy/tree/v0.1.2/docs), [`BiDirectional`](https://github.com/torressa/cspy/blob/v0.1.2/cspy/algorithms/bidirectional.py)).
But again, since you already have the REF in the new format, I would recommend you work with v1.0, the parameter changes are minimal.

I'll leave this issue open, as there are still parts of the documentation that need updating (e.g. the Jane example).

**Comment by tomatoes-prog** [comment]
Thank you, I really appreciate your fast answer!

**Comment by torressa** [comment]
I haven't tested it on windows, but in theory it should also work.

With your custom REFs, you have to really careful with the arguments (e.g. make copies as shown in the example) but also that the REFs are correct. I've had all sorts of errors with both the code being wrong and the REF being incorrect (not doing what you intended).
I'd suggest to get a simple example working (maybe with some print outs), then work your way up.
Also If you can give me a reproducible example, I can give it a try
Worst comes to worst you can revert to v0.1.2 and pass the different functions separately.

Let me know how you get on!

**Comment by torressa** [comment]
- [ ] Jpath example

[REFs page](https://cspy.readthedocs.io/en/latest/ref.html):
- [ ]  assumptions
- [ ]  broken links
- [ ] math formatting
