### ISSUE TITLE
Dominance criteria?

### ISSUE THREAD

**Issue by soomin-woo** [torressa/cspy#96]
Hi @torressa,

I have been using your package pulled a few months ago.
I'm studying how the dominance rule was implemented and read a recent post [here](https://github.com/torressa/cspy/issues/94#issue-1107332812).

Q1) Did you implement the update from the post in the cspy? I don't see a difference on the labelling.cc..
Q2) I would love to design a custom dominance rule in the cspy, but I am unsure where it runs. I see there are functions defined like `checkDominance()`, `fullDominance()`, and `runDominanceEff()`. But I don't see any of these functions used in the functions like `extend()` or `checkFeasibility()`. Am I missing something or the current implementation doesn't run the dominance check?

I've said it before but let me say it again, your work is amaze-balls. 
Thank you!

Soomin

**Comment by torressa** [comment]
Thanks for your king words Soomin! :) 

The dominance check lives only in `checkDominance`, so if you want to change it will be there.
The version of the dominance in the discussion you linked ended up being just slightly different than the previous version (only change is the check for equality in the unreachable nodes). It has not been released or pushed to master yet, but you can see it in the [`dev`](https://github.com/torressa/cspy/blob/ab62a01aac25755ab0ee8a76d9d82e4d76b8a1f8/src/cc/labelling.cc#L158) branch. I have, for example, created a custom dominance check for the pickup and delivery VRP, you can see it in the [`vrpy_patch15`](https://github.com/torressa/cspy/blob/452aaeaca6a63e5ed21b7c0059f6c4b437dbdce4/src/cc/labelling.cc#L239) branch. 

Dominance is ran when you have a new candidate label and want to check that it is not dominated / if it dominates other labels, this is done mostly in `runDominanceEff`, where `checkDominance` is called twice:

https://github.com/torressa/cspy/blob/ab62a01aac25755ab0ee8a76d9d82e4d76b8a1f8/src/cc/labelling.cc#L304-L314

`fullDominance` is kind off strong dominance, as label dominance is checked in both directions. But again, `checkDominance` is where the magic happens.

Label extension (`extend`) and feasibility checks are independent of this. Also, the comments of what each function does, check out the header files `*.h` or the [C++ API](https://cspy.readthedocs.io/en/latest/cc_api/Label.html).

**Comment by soomin-woo** [comment]
Thank you for your awesome reply, @torressa!

**Comment by steveharenberg** [comment]
Hey @torressa, I hit an example with the wrong result and I think this dominance check is not correct for elementary... at least when you have negative costs (or negative resource consumptions).
Here is a small example showing incorrect output:
```
max_res = [100]
min_res = [0]

H = DiGraph(directed=True, n_res=1)
H.add_nodes_from(['Source', 1, 2, 3, 4, 'Sink'])
H.add_edge('Source', 1, res_cost=[1], weight=1)
H.add_edge('Source', 2, res_cost=[1], weight=1)
H.add_edge('Source', 4, res_cost=[1], weight=100)
H.add_edge(1, 3, res_cost=[1], weight=10)
H.add_edge(1, 'Sink', res_cost=[1], weight=1)
H.add_edge(2, 3, res_cost=[1], weight=5)
H.add_edge(2, 'Sink', res_cost=[1], weight=1)
H.add_edge(3, 1, res_cost=[1], weight=-10)
H.add_edge(3, 2, res_cost=[1], weight=-100)
H.add_edge(4, 3, res_cost=[1], weight=1)

# The optimal path should be ['Source', 1, 3, 2, 'Sink']
# -88.0
bidirec = BiDirectional(H, max_res, min_res, elementary=True, direction="forward")
bidirec.run()
print(bidirec.path)
print(bidirec.total_cost)
```

This returns the wrong result because the label with partial path L1=(Source, 2, 3) dominates the label with partial path L2=(Source, 1, 3).

There are no resources and L1.cost = 6 < L2.cost = 11. However, if we were able to expand L2 we would have been able to hit the large negative value link (3,2,-100) which is needed for the optimal path.

Based on an example like this, I don't see how we can prune elementary paths based on dominance checks. With elementary, the partial path matters; e.g., L1 cannot expand into any paths that visit node 2 for instance. If the link weights are only positive, that would be fine because there would be no reason for L2 to expand to node 2. Unfortunately, if there are links that are negative, we don't know whether the label can expand into a state with better cost until it's completely expanded.

Am I missing anything?
